- name: This playbook demonstrates use of dictionary variable 
  hosts: localhost
  vars:
    my_env:
      JAVA_HOME: /usr/lib/java/jdk1.8
      M2_HOME: /usr/share/maven

  tasks:
    - debug: msg="{{item.key}} = {{item.value}}" 
      with_dict: "{{my_env}}"
