- name: Create custom web root folder
  file: path=/var/html state=directory mode=0777

- name: Retrieve IP address of tomcat server
  shell: hostname -i
  register: output

- name: Deploy custom html page into tomcat
  template: src=index.html.j2 dest=/var/html/index.html
