- name: Configure tomcat in Ubuntu to support our custom web root folder
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - Restart tomcat on Ubuntu

- name: Grant permssions to our custom web root folder
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
    - Restart tomcat on Ubuntu
