- name: This playbook will demonstrate build docker images via Ansible playbook
  hosts: localhost

  tasks:

    - name: Delete the existing ubuntu ansible image
      docker_image:
        docker_host: tcp://localhost:4243
        name: "tektutor/ansible-ubuntu"
        state: absent 

    - name: Build ubuntu ansible image
      docker_image:
          docker_host: tcp://localhost:4243
          name: "tektutor/ansible-ubuntu"
          source: build
          build: 
            path: .
            pull: no
            rm: true
          force_source: true
          force_tag: true
          state: present 
