- name: This play will install nginx web server, configure web root folder and deploy custom web page
  hosts: all
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - conf_mgr_tool: Ansible
  tasks:
   - name: Install nginx in the Ubuntu ansible node
     apt: name=nginx state=latest update_cache=yes 

   - name: Create the custom web root folder in Ubuntu ansible node
     file: path=/var/html state=directory mode=0777

   - name: Configure nginx for custom web root folder in Ubuntu ansible node
     copy: src=default dest=/etc/nginx/sites-available/default backup=yes 

   - name: Restart nginx service in Ubuntu ansible node
    #service: name=nginx state=restarted
     shell: service nginx restart

   - name: Deploy custom web page into nginx web server in Ubuntu ansible node
     template: src=index.html.j2 dest=/var/html/index.html
